### ISSUE TITLE
How can I get it ?

### ISSUE THREAD

**Issue by ProTechEx** [fluss45/flussonic#1]
Please let me know how does i can get it.
Please let me how does i can Contact you

**Comment by fluss45** [comment]
Contact on Skype

**Comment by SlaSerX** [comment]
givme skype

**Comment by fluss45** [comment]
kaul.thetv

**Comment by tuipDev219** [comment]
He is a big cheater. He hired freelancers and paid via paypal. After 5 months, he disputed and took all payment away. I already lost 1800$ by him. Don't believe him. I have his skype id . He blocked me.
![Capture](https://user-images.githubusercontent.com/64280377/88084491-19c4c100-cbb7-11ea-8270-8904a021db7a.PNG)

**Comment by fluss45** [comment]
done
